# Simple workflow for deploying static content to GitHub Pages
name: Doxygen

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: get doxygen-awesome-css
        run: |
          mkdir -p docs
          cd docs
          git clone https://github.com/jothepro/doxygen-awesome-css.git
      - name: get doxygen
        run: sudo apt install doxygen graphviz 
      - name: build doxygen
        run: doxygen
      - name: copy images folder
        run: cp -R ./media ./docs/html/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/html'
      - uses: actions/deploy-pages@v4
        id: deployment
